### ISSUE TITLE
pyxel errors out.

### ISSUE THREAD

**Issue by ghost** [bbenne10/pyxel#1]
I tried most of the examples for example.

```
echo "#AAA#BBB#CCC #DDD" | pyxel -
```

I always get the folllowing error.

```
  File "/home/gregf/bin/pyxel", line 51
    t=element), end='')
                   ^
SyntaxError: invalid syntax
```

Python 2.7.11

**Comment by bbenne10** [comment]
Pyxel is intended as a python3 script, but there's no reason we can't support both. Give me just a second to whip up a solution.
